"""initial commerce schema

Revision ID: 0001
Revises:
Create Date: 2026-09-24 17:05:31.681979
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Trigram similarity for typo-tolerant product search. pg_trgm is a *trusted*
    # extension, so the service's own (non-superuser) role may create it.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carts",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("promo_code", sa.String(length=40), nullable=True),
        sa.Column("shipping_address_enc", sa.LargeBinary(), nullable=True),
        sa.Column("ship_country", sa.String(length=2), nullable=True),
        sa.Column("ship_region", sa.String(length=10), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carts")),
        sa.UniqueConstraint("merchant_id", "conversation_id", name=op.f("uq_carts_merchant_id")),
    )
    op.create_table(
        "fx_rates",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("base", sa.String(length=3), nullable=False),
        sa.Column("quote", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rate > 0", name=op.f("ck_fx_rates_rate_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fx_rates")),
    )
    op.create_index("ix_fx_rates_pair_time", "fx_rates", ["base", "quote", "fetched_at"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("caller", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("caller", "key", name=op.f("pk_idempotency_keys")),
    )
    op.create_index(op.f("ix_idempotency_keys_created_at"), "idempotency_keys", ["created_at"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("rating", sa.Numeric(precision=2, scale=1), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english'::regconfig, search_text)", persisted=True),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(op.f("ix_products_merchant_id"), "products", ["merchant_id"], unique=False)
    op.create_index(
        "ix_products_name_trgm",
        "products",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_products_search_vector", "products", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "promotions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=True),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("percent_bps", sa.Integer(), nullable=True),
        sa.Column("amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("min_subtotal_minor", sa.BigInteger(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_redemptions", sa.Integer(), nullable=True),
        sa.Column("redemption_count", sa.Integer(), nullable=False),
        sa.Column("advertised", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(kind = 'percent' AND percent_bps BETWEEN 1 AND 10000) OR (kind = 'fixed' AND amount_minor > 0 AND currency IS NOT NULL)",
            name=op.f("ck_promotions_kind_fields"),
        ),
        sa.CheckConstraint("kind IN ('percent', 'fixed')", name=op.f("ck_promotions_kind_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotions")),
        sa.UniqueConstraint("merchant_id", "code", name=op.f("uq_promotions_merchant_id")),
    )
    op.create_index(op.f("ix_promotions_merchant_id"), "promotions", ["merchant_id"], unique=False)
    op.create_table(
        "shipping_rates",
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("flat_minor", sa.BigInteger(), nullable=False),
        sa.Column("free_from_minor", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("currency", name=op.f("pk_shipping_rates")),
    )
    op.create_table(
        "tax_rates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("region", sa.String(length=10), nullable=True),
        sa.Column("rate_bps", sa.Integer(), nullable=False),
        sa.Column("inclusive", sa.Boolean(), nullable=False),
        sa.CheckConstraint("rate_bps >= 0 AND rate_bps <= 10000", name=op.f("ck_tax_rates_rate_bps_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_rates")),
        sa.UniqueConstraint(
            "country", "region", name=op.f("uq_tax_rates_country"), postgresql_nulls_not_distinct=True
        ),
    )
    op.create_table(
        "quotes",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("cart_id", sa.String(length=40), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("cart_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal_minor", sa.BigInteger(), nullable=False),
        sa.Column("discount_minor", sa.BigInteger(), nullable=False),
        sa.Column("shipping_minor", sa.BigInteger(), nullable=False),
        sa.Column("tax_minor", sa.BigInteger(), nullable=False),
        sa.Column("total_minor", sa.BigInteger(), nullable=False),
        sa.Column("tax_inclusive", sa.Boolean(), nullable=False),
        sa.Column("fx_rate_id", sa.String(length=40), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'superseded', 'expired', 'locked')", name=op.f("ck_quotes_status_valid")
        ),
        sa.CheckConstraint("total_minor >= 0", name=op.f("ck_quotes_total_non_negative")),
        sa.ForeignKeyConstraint(
            ["cart_id"], ["carts.id"], name=op.f("fk_quotes_cart_id_carts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["fx_rate_id"], ["fx_rates.id"], name=op.f("fk_quotes_fx_rate_id_fx_rates")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotes")),
    )
    op.create_index("ix_quotes_cart_status", "quotes", ["cart_id", "status"], unique=False)
    op.create_index("ix_quotes_status_expires", "quotes", ["status", "expires_at"], unique=False)
    op.create_table(
        "skus",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("product_id", sa.String(length=40), nullable=False),
        sa.Column("variant_label", sa.String(length=120), nullable=True),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_skus_product_id_products"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skus")),
    )
    op.create_index(op.f("ix_skus_product_id"), "skus", ["product_id"], unique=False)
    op.create_table(
        "cart_items",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("cart_id", sa.String(length=40), nullable=False),
        sa.Column("sku_id", sa.String(length=40), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_cart_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["cart_id"], ["carts.id"], name=op.f("fk_cart_items_cart_id_carts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], name=op.f("fk_cart_items_sku_id_skus")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_items")),
        sa.UniqueConstraint("cart_id", "sku_id", name=op.f("uq_cart_items_cart_id")),
    )
    op.create_index(op.f("ix_cart_items_cart_id"), "cart_items", ["cart_id"], unique=False)
    op.create_table(
        "inventory",
        sa.Column("sku_id", sa.String(length=40), nullable=False),
        sa.Column("on_hand", sa.Integer(), nullable=False),
        sa.Column("reserved", sa.Integer(), nullable=False),
        sa.CheckConstraint("on_hand >= 0", name=op.f("ck_inventory_on_hand_non_negative")),
        sa.CheckConstraint(
            "reserved >= 0 AND reserved <= on_hand", name=op.f("ck_inventory_reserved_within_on_hand")
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["skus.id"], name=op.f("fk_inventory_sku_id_skus"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("sku_id", name=op.f("pk_inventory")),
    )
    op.create_table(
        "price_book_entries",
        sa.Column("sku_id", sa.String(length=40), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("compare_at_minor", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_price_book_entries_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["skus.id"], name=op.f("fk_price_book_entries_sku_id_skus"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("sku_id", "currency", name=op.f("pk_price_book_entries")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("price_book_entries")
    op.drop_table("inventory")
    op.drop_index(op.f("ix_cart_items_cart_id"), table_name="cart_items")
    op.drop_table("cart_items")
    op.drop_index(op.f("ix_skus_product_id"), table_name="skus")
    op.drop_table("skus")
    op.drop_index("ix_quotes_status_expires", table_name="quotes")
    op.drop_index("ix_quotes_cart_status", table_name="quotes")
    op.drop_table("quotes")
    op.drop_table("tax_rates")
    op.drop_table("shipping_rates")
    op.drop_index(op.f("ix_promotions_merchant_id"), table_name="promotions")
    op.drop_table("promotions")
    op.drop_index("ix_products_search_vector", table_name="products", postgresql_using="gin")
    op.drop_index(
        "ix_products_name_trgm",
        table_name="products",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_products_merchant_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_idempotency_keys_created_at"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_fx_rates_pair_time", table_name="fx_rates")
    op.drop_table("fx_rates")
    op.drop_table("carts")
    # ### end Alembic commands ###
