"""quote locks, reservations, promo redemptions

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 18:55:55.727002
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotion_redemptions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("order_id", sa.String(length=40), nullable=False),
        sa.Column("promotion_id", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('reserved', 'committed', 'released')",
            name=op.f("ck_promotion_redemptions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["promotion_id"], ["promotions.id"], name=op.f("fk_promotion_redemptions_promotion_id_promotions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotion_redemptions")),
        sa.UniqueConstraint("order_id", "promotion_id", name=op.f("uq_promotion_redemptions_order_id")),
    )
    op.create_index(
        op.f("ix_promotion_redemptions_order_id"), "promotion_redemptions", ["order_id"], unique=False
    )
    op.create_table(
        "inventory_reservations",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("order_id", sa.String(length=40), nullable=False),
        sa.Column("sku_id", sa.String(length=40), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('reserved', 'committed', 'released')",
            name=op.f("ck_inventory_reservations_status_valid"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_inventory_reservations_quantity_positive")),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], name=op.f("fk_inventory_reservations_sku_id_skus")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_reservations")),
        sa.UniqueConstraint("order_id", "sku_id", name=op.f("uq_inventory_reservations_order_id")),
    )
    op.create_index(
        op.f("ix_inventory_reservations_order_id"), "inventory_reservations", ["order_id"], unique=False
    )
    op.create_index(
        "ix_inventory_reservations_status_expires",
        "inventory_reservations",
        ["status", "expires_at"],
        unique=False,
    )
    op.add_column("quotes", sa.Column("locked_order_id", sa.String(length=40), nullable=True))
    op.create_unique_constraint(op.f("uq_quotes_locked_order_id"), "quotes", ["locked_order_id"])
    # Manual: Alembic does not diff CHECK constraints. Quotes gain the 'released' state.
    op.drop_constraint(op.f("ck_quotes_status_valid"), "quotes", type_="check")
    op.create_check_constraint(
        op.f("ck_quotes_status_valid"),
        "quotes",
        "status IN ('active', 'superseded', 'expired', 'locked', 'released')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_quotes_status_valid"), "quotes", type_="check")
    op.create_check_constraint(
        op.f("ck_quotes_status_valid"), "quotes", "status IN ('active', 'superseded', 'expired', 'locked')"
    )
    op.drop_constraint(op.f("uq_quotes_locked_order_id"), "quotes", type_="unique")
    op.drop_column("quotes", "locked_order_id")
    op.drop_index("ix_inventory_reservations_status_expires", table_name="inventory_reservations")
    op.drop_index(op.f("ix_inventory_reservations_order_id"), table_name="inventory_reservations")
    op.drop_table("inventory_reservations")
    op.drop_index(op.f("ix_promotion_redemptions_order_id"), table_name="promotion_redemptions")
    op.drop_table("promotion_redemptions")
    # ### end Alembic commands ###
