"""initial checkout schema

Revision ID: 0001
Revises:
Create Date: 2026-09-24 19:03:21.263564
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.String(length=120), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "actor_type IN ('user', 'system', 'webhook', 'service')",
            name=op.f("ck_audit_log_actor_type_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
        sa.UniqueConstraint("hash", name=op.f("uq_audit_log_hash")),
    )
    op.create_index(op.f("ix_audit_log_entity_id"), "audit_log", ["entity_id"], unique=False)
    op.create_table(
        "confirmations",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("quote_id", sa.String(length=40), nullable=False),
        sa.Column("quote_hash", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("order_id", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confirmations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_confirmations_token_hash")),
    )
    op.create_index(op.f("ix_confirmations_quote_id"), "confirmations", ["quote_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("confirmation_id", sa.String(length=40), nullable=False),
        sa.Column("quote_id", sa.String(length=40), nullable=False),
        sa.Column("quote_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_minor", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("settlement", sa.String(length=10), nullable=True),
        sa.Column("stripe_checkout_session_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=True),
        sa.Column("checkout_url", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("settlement IN ('commit', 'release')", name=op.f("ck_orders_settlement_valid")),
        sa.CheckConstraint(
            "status IN ('CREATED', 'AWAITING_PAYMENT', 'PAID', 'FULFILLED', 'PAYMENT_FAILED', 'EXPIRED', 'CANCELED', 'FULFILLMENT_FAILED', 'REFUND_PENDING', 'REFUNDED', 'MANUAL_REVIEW')",
            name=op.f("ck_orders_status_valid"),
        ),
        sa.CheckConstraint("total_minor >= 0", name=op.f("ck_orders_total_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("confirmation_id", name=op.f("uq_orders_confirmation_id")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_orders_idempotency_key")),
        sa.UniqueConstraint("quote_id", name=op.f("uq_orders_quote_id")),
        sa.UniqueConstraint("stripe_checkout_session_id", name=op.f("uq_orders_stripe_checkout_session_id")),
    )
    op.create_index(op.f("ix_orders_conversation_id"), "orders", ["conversation_id"], unique=False)
    op.create_index(
        "ix_orders_settlement_pending",
        "orders",
        ["settlement"],
        unique=False,
        postgresql_where="settlement IS NOT NULL",
    )
    op.create_index("ix_orders_status_created", "orders", ["status", "created_at"], unique=False)
    op.create_table(
        "webhook_inbox",
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=120), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_webhook_inbox")),
    )
    op.create_index(
        "ix_webhook_inbox_pending",
        "webhook_inbox",
        ["received_at"],
        unique=False,
        postgresql_where="processed_at IS NULL",
    )
    # ### end Alembic commands ###
    # Manual: the audit log is append-only at the database level, for every role including the owner.
    op.execute(
        """
        CREATE FUNCTION audit_log_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only (% blocked)', TG_OP;
        END;
        $$;
        """
    )
    op.execute(
        "CREATE TRIGGER audit_log_append_only BEFORE UPDATE OR DELETE OR TRUNCATE ON audit_log "
        "FOR EACH STATEMENT EXECUTE FUNCTION audit_log_immutable()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_webhook_inbox_pending", table_name="webhook_inbox", postgresql_where="processed_at IS NULL"
    )
    op.drop_table("webhook_inbox")
    op.drop_index("ix_orders_status_created", table_name="orders")
    op.drop_index(
        "ix_orders_settlement_pending", table_name="orders", postgresql_where="settlement IS NOT NULL"
    )
    op.drop_index(op.f("ix_orders_conversation_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_confirmations_quote_id"), table_name="confirmations")
    op.drop_table("confirmations")
    op.drop_index(op.f("ix_audit_log_entity_id"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
