"""refunds reconciliation and alerting

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 11:49:12.398049
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("stripe_refund_id", sa.String(length=255), nullable=True))
    op.add_column("orders", sa.Column("refund_status", sa.String(length=20), nullable=True))
    op.add_column("orders", sa.Column("attention_alerted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("orders", sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(op.f("uq_orders_stripe_refund_id"), "orders", ["stripe_refund_id"])
    # ### end Alembic commands ###
    # Settlement can now also owe a 'void' (promotion use given back after a refund).
    op.drop_constraint(op.f("ck_orders_settlement_valid"), "orders", type_="check")
    op.create_check_constraint(
        op.f("ck_orders_settlement_valid"), "orders", "settlement IN ('commit', 'release', 'void')"
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_orders_settlement_valid"), "orders", type_="check")
    op.create_check_constraint(
        op.f("ck_orders_settlement_valid"), "orders", "settlement IN ('commit', 'release')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_orders_stripe_refund_id"), "orders", type_="unique")
    op.drop_column("orders", "reconciled_at")
    op.drop_column("orders", "attention_alerted_at")
    op.drop_column("orders", "refund_status")
    op.drop_column("orders", "stripe_refund_id")
    # ### end Alembic commands ###
